channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::_libgcc_mutex=0.1=conda_forge
  - conda-forge::_openmp_mutex=4.5=2_gnu
  - conda-forge::ca-certificates=2024.8.30=hbcca054_0
  - conda-forge::ld_impl_linux-64=2.43=h712a8e2_2
  - conda-forge::libffi=3.3=h58526e2_2
  - conda-forge::libgcc=14.2.0=h77fa898_1
  - conda-forge::libgcc-ng=14.2.0=h69a702a_1
  - conda-forge::libgomp=14.2.0=h77fa898_1
  - conda-forge::libsqlite=3.46.0=hde9e2c9_0
  - conda-forge::libstdcxx=14.2.0=hc0a3c3a_1
  - conda-forge::libstdcxx-ng=14.2.0=h4852527_1
  - conda-forge::libzlib=1.2.13=h4ab18f5_6
  - conda-forge::ncurses=6.5=he02047a_1
  - conda-forge::openssl=1.1.1w=hd590300_0
  - conda-forge::pip=24.3.1=pyh8b19718_0
  - conda-forge::python=3.9.5=h49503c6_0_cpython
  - conda-forge::readline=8.2=h8228510_1
  - conda-forge::setuptools=75.3.0=pyhd8ed1ab_0
  - conda-forge::sqlite=3.46.0=h6d4b2fc_0
  - conda-forge::tk=8.6.13=noxft_h4845f30_101
  - conda-forge::tzdata=2024b=hc8b5060_0
  - conda-forge::wheel=0.45.0=pyhd8ed1ab_0
  - conda-forge::xz=5.2.6=h166bdaf_0
  - conda-forge::zlib=1.2.13=h4ab18f5_6
